#
#Dockerfile for aria2
#

FROM alpine:latest
LABEL maintainer="ksana410 <ddxiong0410@gmail.com>"
ENV PUID=1000
ENV PGID=100
ENV SECRET=password
RUN apk update && \
    apk add aria2 && \
    apk add wget && \
    rm /var/cache/apk/* && \
    mkdir -p /aria2/conf && \
    mkdir /aria2/downloads
VOLUME [ "/aria2/conf","/aria2/downloads" ]

ADD start.sh /aria2
ADD aria2.conf /aria2
ADD dht.dat /aria2
RUN chmod +x /aria2/start.sh
EXPOSE 6800 6881 6881/udp
CMD set -xe &&\
    /aria2/start.sh
